spring:
  application:
    name: sm-kafka-administrator

kafka:
  bootstrap:
    url: localhost:9092
  topics:
    transactions:
      name: simoes-transactions
      partitions: 5
      replicas: 1
    transactions-validator:
      name: simoes-transactions-validator
      partitions: 5
      replicas: 1
