spring:
  application:
    name: sm-consumer-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: simoes-transactions-consumer

server:
  port: 5000

topics:
  transactions:
    name: simoes-transactions