spring:
  application:
    name: sm-consumer-service
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      specific:
        avro:
          reader: true
      schema:
        registry:
          url: http://localhost:8081
    consumer:
      group-id: simoes-transactions-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      enable-auto-commit: false
    listener:
      ack-mode: MANUAL_IMMEDIATE

server:
  port: 5000

topics:
  transactions:
    name: simoes-transactions