spring:
  application:
    name: sm-consumer-service

server:
  port: 5000

kafka:
  bootstrap:
    url: localhost:9092
  topics:
    transactions:
      name: simoes-transactions
      groupId: simoes-transactions-consumer
    transactions-validator:
      name: simoes-transactions-validator
      groupId: simoes-transactions-validator-consumer