spring:
  application:
    name: sm-producer-service

kafka:
  bootstrap:
    url: localhost:9092
  topics:
    transactions:
      name: simoes-transactions
    transactions-validator:
      name: simoes-transactions-validator
